### ISSUE TITLE
Refactor interaction with ElasticSearch

### ISSUE THREAD

**Issue by bbockelm** [opensciencegrid/StashCache#19]
We currently send to ElasticSearch inline from several locations.  See:

https://github.com/opensciencegrid/StashCache/blob/master/bin/stashcp#L63

Let's factor this out into a standalone function call (or a separate module).

**Comment by djw8605** [comment]
There's a lot of information we need to send to ES, that needs to be filled in.  So either we:

* Make a long function call, or with `**kwargs`
* Pass the payload object as a object, removing the multi-process calls only.

**Comment by bbockelm** [comment]
I think you can pull out a few of the common pieces of the payload generation:
- You can always auto-generate the `timestamp` field.
- `host` and `cache` appear to be identical.
- Timestamp generation is strange.  It appears to be a strange way to say `int(time.time())*1000`
(there might be other fields that are redundant)

**Comment by djw8605** [comment]
My question is, why would you multiply by 1000?  So it's milliseconds since the unix epoch?  Seems odd?

**Comment by illingwo** [comment]
Milliseconds since the epoch is Javascript's standard representation for time values.

**Comment by djw8605** [comment]
Ah, so it's a requirement from Elasticsearch.  I do see now that elasticsearch represents timestamps as milliseconds since epoch.

**Comment by bbockelm** [comment]
That's the default representation - there's a few other ways to force ElasticSearch to do the conversion for you.  But yeah - might as well use the default.

**Comment by djw8605** [comment]
Merged #31
