### ISSUE TITLE
Run pylintrc for stashcp

### ISSUE THREAD

**Issue by bbockelm** [opensciencegrid/StashCache#27]
We should run pylintrc on `stashcp` as part of the Travis-CI build; fail things if we aren't sufficiently happy.

**Comment by djw8605** [comment]
Working on it in #33

**Comment by bbockelm** [comment]
@djw8605 - can you open a separate ticket to actually fail the build if there are concerns from `pylint`?  We might have to add a project-private `pylintrc` in order to make it ignore some of the more annoying code formatting items.
