### ISSUE TITLE
Make forward slash at beginning optional

### ISSUE THREAD

**Issue by djw8605** [opensciencegrid/StashCache#36]
In the old client, the forward slash at the beginning of the source path was optional.  We should carry that forward so the transition is easier.

**Comment by bbockelm** [comment]
As in, someone could simply write `bbockelm/foo/bar` instead of `/bbockelm/foo/bar`?

We should emit a warning if the forward slash is missing and include a formal deprecation timeline in the warning.

**Comment by djw8605** [comment]
More like `user/bbockelm/foo/bar`, still have to start with `user`, but, yes.

**Comment by djw8605** [comment]
Merged in #37
