### ISSUE TITLE
Change stashcp geo api URLs

### ISSUE THREAD

**Issue by DrDaveD** [opensciencegrid/StashCache#72]
Instead of sending a max-age=0 http header, please change stashcp to use a per worker-node unique string for the "append-text".  I suggest appending "-" str(uuid.getnode()) which puts on a mac address of the worker node.  Ideally it would be a unique string per site, but that is much more challenging to calculate.  cvmfs passes in the name of the local site squid and uses the result from there.

**Comment by bbockelm** [comment]
Hi,

Note that because all of FNAL and Nebraska run pilots inside Docker, I believe that pilots would all have the same MAC addresses.

Brian

**Comment by djw8605** [comment]
We do have a site_name attribute that could be useful.  But, it can be 'unknown', in which case we could fall back to the uuid?

https://github.com/opensciencegrid/StashCache/blob/master/bin/stashcp#L30

**Comment by bbockelm** [comment]
That approach would work, I think.

**Comment by DrDaveD** [comment]
Sure, the site name would be great, and fall back to the mac address if it is not unique.

If we fall back to the mac address, as long as a docker mac address is unique per site, having it be the same for the whole site would actually be a good thing.

Some sites also set a squid name in an OSG environment variable, I forget what it is exactly.  If you could use that squid, it would greatly reduce the number of queries to the stratum 1s.

**Comment by djw8605** [comment]
So, a fallback system:

1. OSG_SITE_NAME
2. http_proxy
3. uuid with mac address.

?

-Derek

**Comment by DrDaveD** [comment]
The variable for the http proxy is OSG_SQUID_LOCATION which probably contains http:// and :3128 at the end, I am not sure.  If you assign that value also to the http_proxy environment variable, urllib2 should automatically try it.  It might fail though, and if it does you can go through the list of stratum 1s again without http_proxy set.

You should be setting the urllib2 timeout parameter as well.  I think timeout=10 is reasonable, that's what the cvmfs client uses.

**Comment by DrDaveD** [comment]
Ok nothing happened on this, and this is really causing problems for our stratum 1 monitoring.  Now we're getting lots of hits from Mancester in the UK to the BNL stratum 1 by stashcp.

I have a new plan, and would like it to be implemented as soon as possible.  I have enabled the geo api on the wlcg-wpad servers, which already had the cvmfs-server software installed.  They are already designed for getting contacted by lots of servers around the grid, unlike the stratum 1s which are only intended to be contacted by squids.  All I had to do was make an apache config file similar to the one created on stratum 1s.

The URLs are http://wlcg-wpad.cern.ch/api/v1.0/geo/stashcp/... and http://wlcg-wpad.fnal.gov/api/v1.0/geo/stashcp/....    Select one or the other randomly, and try both if one fails.  In fact, you should try both IP addresses in the round-robin of the one you select if the first one fails within 10 seconds, before moving on to the second one.

Even with these servers, I hope the use of stashcp gets kept to a minimum.  osgstorage.org repositories should be used first if they're available.  Usage of the wlcg-wpad wpad.dat service is growing, and we have a plan with that for large sites to supply their own servers to offload the central servers.  I don't see that happening for the geo api service, so I hope that it doesn't grow as much as I expect use of the wpad service to grow.

**Comment by DrDaveD** [comment]
Fixed through #79
