### ISSUE TITLE
stashcp only tries one stashcache server

### ISSUE THREAD

**Issue by DrDaveD** [opensciencegrid/StashCache#81]
stashcp only looks up the closest stashcache server and never tries the next one, if it isn't copying through cvmfs.  This is not very robust!

**Comment by DrDaveD** [comment]
I did a test without cvmfs (using -r /user/bbockelm/public) and the first stashcache did fail, then it switched to directly connect to stash.osgconnect.net.  If that's the desired behavior, I guess it is OK.

**Comment by djw8605** [comment]
Yup, makes sense, if the cache fails, then download from the origin.

**Comment by DrDaveD** [comment]
Why shouldn't it try the next closest stash cache instead of going directly to the origin?

**Comment by djw8605** [comment]
It certainly could.  Actually, for HTTP, it tries the closest 2 caches before giving up.  I could certainly add "num caches to try" to stashcp.

**Comment by matyasselmeci** [comment]
#118 fixed this.
